// assetInfo.js
export const initialAdditionalCryptos = [
  {
    name: "Arbitrum",
    shortName: "ARB",
    balance: "0.0",
    icon: require("../assets/icon/ARBIcon.png"),
    cardImage: require("../assets/CardBg/Card15.png"),
    address: "",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    queryChainName: "arbitrum",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    queryChainName: "arbitrum",
    type: "ARBITRUM",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    queryChainName: "arbitrum",
    type: "ARBITRUM",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    queryChainName: "arbitrum",
    type: "ARBITRUM",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Aurora",
    shortName: "AURORA",
    balance: "0.0",
    icon: require("../assets/icon/AURORAIcon.png"),
    cardImage: require("../assets/CardBg/Card10.png"),
    address: "",
    chain: "Aurora",
    chainShortName: "AURORA",
    queryChainShortName: "AURORA",
    chainIcon: require("../assets/icon/AURORAIcon.png"),
    queryChainName: "aurora",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Avalanche",
    shortName: "AVAX",
    balance: "0.0",
    icon: require("../assets/icon/AVAXIcon.png"),
    cardImage: require("../assets/CardBg/Card21.png"),
    address: "",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    queryChainName: "avalanchec",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    queryChainName: "avalanchec",
    type: "AVALANCHE",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    queryChainName: "avalanchec",
    type: "AVALANCHE",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    queryChainName: "avalanchec",
    type: "AVALANCHE",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Bitcoin",
    shortName: "BTC",
    balance: "0.0",
    icon: require("../assets/icon/BTCIcon.png"),
    cardImage: require("../assets/CardBg/Card22.png"),
    address: "",
    chain: "Bitcoin",
    chainShortName: "BTC",
    queryChainShortName: "BTC",
    chainIcon: require("../assets/icon/BTCIcon.png"),
    queryChainName: "bitcoin",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Bitcoin Cash",
    shortName: "BCH",
    balance: "0.0",
    icon: require("../assets/BitcoinCashIcon.png"),
    cardImage: require("../assets/CardBg/Card8.png"),
    address: "",
    chain: "BCH",
    chainShortName: "BCH",
    queryChainShortName: "BCH",
    chainIcon: require("../assets/icon/BCHIcon.png"),
    queryChainName: "bitcoincash",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Binance",
    shortName: "BNB",
    balance: "0.0",
    icon: require("../assets/icon/BNBIcon.png"),
    cardImage: require("../assets/CardBg/Card41.png"),
    address: "",
    chain: "Binance Smart Chain",
    chainShortName: "BSC",
    queryChainShortName: "BSC",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    queryChainName: "smartchain",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Binance Smart Chain",
    chainShortName: "BSC",
    queryChainShortName: "BSC",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    queryChainName: "smartchain",
    type: "BEP20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Binance Smart Chain",
    chainShortName: "BSC",
    queryChainShortName: "BSC",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    queryChainName: "smartchain",
    type: "BEP20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x55d398326f99059fF775485246999027B3197955",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Binance Smart Chain",
    chainShortName: "BSC",
    queryChainShortName: "BSC",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    queryChainName: "smartchain",
    type: "BEP20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Celo",
    shortName: "CELO",
    balance: "0.0",
    icon: require("../assets/icon/CELOIcon.png"),
    cardImage: require("../assets/CardBg/Card111.png"),
    address: "",
    chain: "Celo",
    chainShortName: "CELO",
    queryChainShortName: "CELO",
    chainIcon: require("../assets/icon/CELOIcon.png"),
    queryChainName: "celo",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Ethereum",
    shortName: "ETH",
    balance: "0.0",
    icon: require("../assets/icon/ETHIcon.png"),
    cardImage: require("../assets/CardBg/Card35.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "ERC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "ERC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "ERC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Polygon",
    shortName: "POL",
    balance: "0.0",
    icon: require("../assets/icon/PolygonIcon.png"),
    cardImage: require("../assets/CardBg/Card18.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "ERC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    queryChainName: "polygon",
    type: "POLYGON",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    queryChainName: "polygon",
    type: "POLYGON",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    queryChainName: "polygon",
    type: "POLYGON",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "BNB",
    shortName: "BNB",
    balance: "0.0",
    icon: require("../assets/icon/BNBIcon.png"),
    cardImage: require("../assets/CardBg/Card41.png"),
    address: "",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    queryChainName: "ethereum",
    type: "ERC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xB8c77482e45F1F44dE1745F52C74426C631bDD52",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Ethereum Classic",
    shortName: "ETC",
    balance: "0.0",
    icon: require("../assets/icon/ETCIcon.png"),
    cardImage: require("../assets/CardBg/Card62.png"),
    address: "",
    chain: "ETC",
    chainShortName: "ETC",
    queryChainShortName: "ETC",
    chainIcon: require("../assets/icon/ETCIcon.png"),
    queryChainName: "classic",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Fantom",
    shortName: "FTM",
    balance: "0.0",
    icon: require("../assets/icon/FTMIcon.png"),
    cardImage: require("../assets/CardBg/Card45.png"),
    address: "",
    chain: "Fantom",
    chainShortName: "FTM",
    queryChainShortName: "FTM",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    queryChainName: "fantom",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Fantom",
    chainShortName: "Fantom",
    queryChainShortName: "Fantom",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    queryChainName: "fantom",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Fantom",
    chainShortName: "Fantom",
    queryChainShortName: "Fantom",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    queryChainName: "fantom",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Huobi Token",
    shortName: "HTX",
    balance: "0.0",
    icon: require("../assets/icon/HTIcon.png"),
    cardImage: require("../assets/CardBg/Card56.png"),
    address: "",
    chain: "Huobi ECO Chain",
    chainShortName: "HTX",
    queryChainShortName: "HTX",
    chainIcon: require("../assets/icon/HTIcon.png"),
    queryChainName: "cronos",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "IoTeX",
    shortName: "IOTX",
    balance: "0.0",
    icon: require("../assets/icon/IOTXIcon.png"),
    cardImage: require("../assets/CardBg/Card78.png"),
    address: "",
    chain: "IoTeX Mainnet",
    chainShortName: "IOTX",
    queryChainShortName: "IOTX",
    chainIcon: require("../assets/icon/IOTXIcon.png"),
    queryChainName: "iotexevm",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Litecoin",
    shortName: "LTC",
    balance: "0.0",
    icon: require("../assets/icon/LTCIcon.png"),
    cardImage: require("../assets/CardBg/Card100.png"),
    address: "",
    chain: "Litecoin",
    chainShortName: "LTC",
    queryChainShortName: "LTC",
    chainIcon: require("../assets/icon/LTCIcon.png"),
    queryChainName: "litecoin",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "OKT",
    shortName: "OKT",
    balance: "0.0",
    icon: require("../assets/icon/OKTIcon.png"),
    cardImage: require("../assets/CardBg/Card106.png"),
    address: "",
    chain: "OKX Chain",
    chainShortName: "OKT",
    queryChainShortName: "OKT",
    chainIcon: require("../assets/icon/OKTIcon.png"),
    queryChainName: "okc",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "OKX Chain",
    chainShortName: "OKT",
    queryChainShortName: "OKT",
    chainIcon: require("../assets/icon/OKTIcon.png"),
    queryChainName: "okc",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xc946DAf81b08146B1C7A8Da2A851Ddf2B3EAaf85",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "OKX Chain",
    chainShortName: "OKT",
    queryChainShortName: "OKT",
    chainIcon: require("../assets/icon/OKTIcon.png"),
    queryChainName: "okc",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x382bB369d343125BfB2117af9c149795C6C65C50",
    Decimals: "18",
    publicKey: "",
  },
  {
    name: "Optimism",
    shortName: "OP",
    balance: "0.0",
    icon: require("../assets/icon/OPIcon.png"),
    cardImage: require("../assets/CardBg/Card81.png"),
    address: "",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    queryChainName: "optimisim",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "USD Coin (Bridged from Ethereum)",
    shortName: "USDC.e",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    queryChainName: "optimisim",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    queryChainName: "optimisim",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Dai",
    shortName: "DAI",
    balance: "0.0",
    icon: require("../assets/icon/DAIIcon.png"),
    cardImage: require("../assets/CardBg/Card55.png"),
    address: "",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    queryChainName: "optimisim",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
    Decimals: "18",
    publicKey: "",
  },

  {
    name: "Polygon",
    shortName: "POL",
    balance: "0.0",
    icon: require("../assets/icon/PolygonIcon.png"),
    cardImage: require("../assets/CardBg/Card18.png"),
    address: "",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    queryChainName: "polygon",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Ripple",
    shortName: "XRP",
    balance: "0.0",
    icon: require("../assets/icon/XRPIcon.png"),
    cardImage: require("../assets/CardBg/Card84.png"),
    address: "",
    chain: "Ripple",
    chainShortName: "XRP",
    queryChainShortName: "XRP",
    chainIcon: require("../assets/icon/XRPIcon.png"),
    queryChainName: "ripple",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Solana",
    shortName: "SOL",
    balance: "0.0",
    icon: require("../assets/icon/SOLIcon.png"),
    cardImage: require("../assets/CardBg/Card2.png"),
    address: "",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    queryChainName: "solana",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    queryChainName: "solana",
    type: "SPL",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    queryChainName: "solana",
    type: "SPL",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    Decimals: "6",
    publicKey: "",
  },
  {
    name: "Tron",
    shortName: "TRX",
    balance: "0.0",
    icon: require("../assets/icon/TRXIcon.png"),
    cardImage: require("../assets/CardBg/Card97.png"),
    address: "",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    queryChainName: "tron",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    balance: "0.0",
    icon: require("../assets/icon/USDCIcon.png"),
    cardImage: require("../assets/CardBg/Card107.png"),
    address: "",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    queryChainName: "tron",
    type: "TRC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8",
    Decimals: "6",
    publicKey: "",
  },

  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    queryChainName: "tron",
    type: "TRC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    Decimals: "6",
    publicKey: "",
  },

  {
    name: "zkSync Era",
    shortName: "ZKSYNC",
    balance: "0.0",
    icon: require("../assets/icon/ZKSIcon.png"),
    cardImage: require("../assets/CardBg/Card94.png"),
    address: "",
    chain: "ZKSYNC",
    chainShortName: "ZKSYNC",
    queryChainShortName: "ZKSYNC",
    chainIcon: require("../assets/icon/ZKSIcon.png"),
    queryChainName: "zksync",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },

  // 下面是新增的
  {
    name: "Cosmos",
    shortName: "ATOM",
    balance: "0.0",
    icon: require("../assets/icon/ATOMIcon.png"),
    cardImage: require("../assets/CardBg/Card38.png"),
    address: "",
    chain: "Cosmos",
    chainShortName: "ATOM",
    queryChainShortName: "ATOM",
    chainIcon: require("../assets/icon/ATOMIcon.png"),
    queryChainName: "cosmos",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Celestia",
    shortName: "CEL",
    balance: "0.0",
    icon: require("../assets/icon/TIAIcon.png"),
    cardImage: require("../assets/CardBg/Card51.png"),
    address: "",
    chain: "Celestia",
    chainShortName: "CEL",
    queryChainShortName: "CEL",
    chainIcon: require("../assets/icon/TIAIcon.png"),
    queryChainName: "celestia",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Crypto.org Coin",
    shortName: "CRO",
    balance: "0.0",
    icon: require("../assets/icon/CROIcon.png"),
    cardImage: require("../assets/CardBg/Card11.png"),
    address: "",
    chain: "Crypto.org",
    chainShortName: "CRO",
    queryChainShortName: "CRO",
    chainIcon: require("../assets/icon/CROIcon.png"),
    queryChainName: "cryptoorg",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    balance: "0.0",
    icon: require("../assets/icon/USDTIcon.png"),
    cardImage: require("../assets/CardBg/Card101.png"),
    address: "",
    chain: "Crypto.org",
    chainShortName: "CRO",
    queryChainShortName: "CRO",
    chainIcon: require("../assets/icon/CROIcon.png"),
    queryChainName: "cryptoorg",
    type: "CRC20",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "0x66e428c3f67a68878562e79A0234c1F83c208770",
    Decimals: "6",
    publicKey: "",
  },

  {
    name: "Juno",
    shortName: "JUNO",
    balance: "0.0",
    icon: require("../assets/icon/JUNOIcon.png"),
    cardImage: require("../assets/CardBg/Card91.png"),
    address: "",
    chain: "Juno",
    chainShortName: "JUNO",
    queryChainShortName: "JUNO",
    chainIcon: require("../assets/icon/JUNOIcon.png"),
    queryChainName: "juno",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Osmosis",
    shortName: "OSMO",
    balance: "0.0",
    icon: require("../assets/icon/OSMOIcon.png"),
    cardImage: require("../assets/CardBg/Card104.png"),
    address: "",
    chain: "Osmosis",
    chainShortName: "OSMO",
    queryChainShortName: "OSMO",
    chainIcon: require("../assets/icon/OSMOIcon.png"),
    queryChainName: "osmosis",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Gnosis",
    shortName: "GNO",
    balance: "0.0",
    icon: require("../assets/icon/GNOIcon.png"),
    cardImage: require("../assets/CardBg/Card36.png"),
    address: "",
    chain: "Gnosis",
    chainShortName: "GNO",
    queryChainShortName: "GNO",
    chainIcon: require("../assets/icon/GNOIcon.png"),
    queryChainName: "gnosis",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Linea",
    shortName: "LINEA",
    balance: "0.0",
    icon: require("../assets/icon/LINEAIcon.png"),
    cardImage: require("../assets/CardBg/Card6.png"),
    address: "",
    chain: "Linea",
    chainShortName: "LINEA",
    queryChainShortName: "LINEA",
    chainIcon: require("../assets/icon/LINEAIcon.png"),
    queryChainName: "linea",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Ronin",
    shortName: "RON",
    balance: "0.0",
    icon: require("../assets/icon/RONIcon.png"),
    cardImage: require("../assets/CardBg/Card83.png"),
    address: "",
    chain: "Ronin",
    chainShortName: "RON",
    queryChainShortName: "RON",
    chainIcon: require("../assets/icon/RONIcon.png"),
    queryChainName: "ronin",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "Aptos",
    shortName: "APT",
    balance: "0.0",
    icon: require("../assets/icon/APTIcon.png"),
    cardImage: require("../assets/CardBg/Card14.png"),
    address: "",
    chain: "Aptos",
    chainShortName: "APT",
    queryChainShortName: "APT",
    chainIcon: require("../assets/icon/APTIcon.png"),
    queryChainName: "aptos",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
  {
    name: "SUI",
    shortName: "SUI",
    balance: "0.0",
    icon: require("../assets/icon/SUIIcon.png"),
    cardImage: require("../assets/CardBg/Card108.png"),
    address: "",
    chain: "SUI",
    chainShortName: "SUI",
    queryChainShortName: "SUI",
    chainIcon: require("../assets/icon/SUIIcon.png"),
    queryChainName: "sui",
    type: "coin",
    fee: "0.0",
    valueUsd: "0.0",
    priceUsd: "0.0",
    contractAddress: "",
    Decimals: "",
    publicKey: "",
  },
];
