// cryptosData.js
export const initialAdditionalCryptos = [
  {
    name: "Arbitrum",
    shortName: "ARB",
    balance: "0.0",
    icon: require("../assets/icon/ARBIcon.png"),
    cardImage: require("../assets/CardBg/Card15.png"),
    address: " ",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.2",
  },
  {
    name: "Aurora",
    shortName: "AURORA",
    balance: "0.0",
    icon: require("../assets/icon/AURORAIcon.png"),
    cardImage: require("../assets/CardBg/Card10.png"),
    address: " ",
    chain: "Aurora",
    chainShortName: "AURORA",
    queryChainShortName: "AURORA",
    chainIcon: require("../assets/icon/AURORAIcon.png"),
    tokenType: "AURORA",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.3",
  },
  {
    name: "Avalanche",
    shortName: "AVAX",
    balance: "0.0",
    icon: require("../assets/icon/AVAXIcon.png"),
    cardImage: require("../assets/CardBg/Card21.png"),
    address: " ",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    tokenType: "AVAX",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "10.0",
  },
  {
    name: "Bitcoin",
    shortName: "BTC",
    balance: "0.0",
    icon: require("../assets/icon/BTCIcon.png"),
    cardImage: require("../assets/CardBg/Card22.png"),
    address: " ",
    chain: "Bitcoin",
    chainShortName: "BTC",
    queryChainShortName: "BTC",
    chainIcon: require("../assets/icon/BTCIcon.png"),
    tokenType: "BTC",
    fee: "0.0001",
    valueUsd: "0.0",
    priceUsd: "30000.0",
  },
  {
    name: "Bitcoin Cash",
    shortName: "BCH",
    balance: "0.0",
    icon: require("../assets/BitcoinCashIcon.png"),
    cardImage: require("../assets/CardBg/Card8.png"),
    address: " ",
    chain: "BCH",
    chainShortName: "BCH",
    queryChainShortName: "BCH",
    chainIcon: require("../assets/icon/BCHIcon.png"),
    tokenType: "BCH",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "Binance",
    shortName: "BNB",
    balance: "0.0",
    icon: require("../assets/icon/BNBIcon.png"),
    cardImage: require("../assets/CardBg/Card41.png"),
    address: " ",
    chain: "BNB Smart Chain",
    chainShortName: "BNB",
    queryChainShortName: "BNB",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    tokenType: "BEP20",
    fee: "0.005",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "Celo",
    shortName: "CELO",
    balance: "0.0",
    icon: require("../assets/icon/CELOIcon.png"),
    cardImage: require("../assets/CardBg/Card111.png"),
    address: " ",
    chain: "Celo",
    chainShortName: "CELO",
    queryChainShortName: "CELO",
    chainIcon: require("../assets/icon/CELOIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Ethereum",
    shortName: "ETH",
    balance: "0.0",
    icon: require("../assets/icon/ETHIcon.png"),
    cardImage: require("../assets/CardBg/Card35.png"),
    address: " ",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "2000.0",
  },
  {
    name: "Ethereum Classic",
    shortName: "ETC",
    balance: "0.0",
    icon: require("../assets/icon/ETCIcon.png"),
    cardImage: require("../assets/CardBg/Card62.png"),
    address: " ",
    chain: "ETC",
    chainShortName: "ETC",
    queryChainShortName: "ETC",
    chainIcon: require("../assets/icon/ETCIcon.png"),
    tokenType: "ETC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "15.0",
  },
  {
    name: "Fantom",
    shortName: "FTM",
    balance: "0.0",
    icon: require("../assets/icon/FTMIcon.png"),
    cardImage: require("../assets/CardBg/Card45.png"),
    address: " ",
    chain: "Fantom",
    chainShortName: "FTM",
    queryChainShortName: "FTM",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Huobi Token",
    shortName: "HTX",
    balance: "0.0",
    icon: require("../assets/icon/HTIcon.png"),
    cardImage: require("../assets/CardBg/Card56.png"),
    address: " ",
    chain: "Huobi ECO Chain",
    chainShortName: "HTX",
    queryChainShortName: "HTX",
    chainIcon: require("../assets/icon/HTIcon.png"),
    tokenType: "ERC20",
    fee: "0.002",
    valueUsd: "0.0",
    priceUsd: "7.0",
  },
  {
    name: "IoTeX",
    shortName: "IOTX",
    balance: "0.0",
    icon: require("../assets/icon/IOTXIcon.png"),
    cardImage: require("../assets/CardBg/Card78.png"),
    address: " ",
    chain: "IoTeX Mainnet",
    chainShortName: "IOTX",
    queryChainShortName: "IOTX",
    chainIcon: require("../assets/icon/IOTXIcon.png"),
    tokenType: "IOTX",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "Litecoin",
    shortName: "LTC",
    balance: "0.0",
    icon: require("../assets/icon/LTCIcon.png"),
    cardImage: require("../assets/CardBg/Card100.png"),
    address: " ",
    chain: "Litecoin",
    chainShortName: "LTC",
    queryChainShortName: "LTC",
    chainIcon: require("../assets/icon/LTCIcon.png"),
    tokenType: "LTC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "150.0",
  },
  {
    name: "OKB",
    shortName: "OKB",
    balance: "0.0",
    icon: require("../assets/icon/OKBIcon.png"),
    cardImage: require("../assets/CardBg/Card106.png"),
    address: " ",
    chain: "OKX Chain",
    chainShortName: "OKB",
    queryChainShortName: "OKB",
    chainIcon: require("../assets/icon/OKBIcon.png"),
    tokenType: "ERC20",
    fee: "0.003",
    valueUsd: "0.0",
    priceUsd: "20.0",
  },
  {
    name: "Optimism",
    shortName: "OP",
    balance: "0.0",
    icon: require("../assets/icon/OPIcon.png"),
    cardImage: require("../assets/CardBg/Card81.png"),
    address: " ",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Polygon",
    shortName: "POL",
    balance: "0.0",
    icon: require("../assets/icon/PolygonIcon.png"),
    cardImage: require("../assets/CardBg/Card18.png"),
    address: " ",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.0",
  },
  {
    name: "Ripple",
    shortName: "XRP",
    balance: "0.0",
    icon: require("../assets/icon/XRPIcon.png"),
    cardImage: require("../assets/CardBg/Card84.png"),
    address: " ",
    chain: "Ripple",
    chainShortName: "XRP",
    queryChainShortName: "XRP",
    chainIcon: require("../assets/icon/XRPIcon.png"),
    tokenType: "XRP",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Solana",
    shortName: "SOL",
    balance: "0.0",
    icon: require("../assets/icon/SOLIcon.png"),
    cardImage: require("../assets/CardBg/Card2.png"),
    address: " ",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    tokenType: "SOL",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "25.0",
  },
  {
    name: "Tron",
    shortName: "TRX",
    balance: "0.0",
    icon: require("../assets/icon/TRXIcon.png"),
    cardImage: require("../assets/CardBg/Card97.png"),
    address: " ",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    tokenType: "TRC20",
    fee: "0.1",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "zkSync Era",
    shortName: "ZKSYNC",
    balance: "0.0",
    icon: require("../assets/icon/ZKSIcon.png"),
    cardImage: require("../assets/CardBg/Card94.png"),
    address: " ",
    chain: "ZKSYNC",
    chainShortName: "ZKSYNC",
    queryChainShortName: "ZKSYNC",
    chainIcon: require("../assets/icon/ZKSIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
];
