// cryptosData.js
export const initialAdditionalCryptos = [
  {
    name: "Arbitrum",
    shortName: "ARB",
    balance: "0.0",
    icon: require("../assets/icon/ARBIcon.png"),
    cardImage: require("../assets/CardBg/Card15.png"),
    address: "Click the Verify Address Button",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.2",
  },
  {
    name: "Aurora",
    shortName: "AURORA",
    balance: "0.0",
    icon: require("../assets/icon/AURORAIcon.png"),
    cardImage: require("../assets/CardBg/Card10.png"),
    address: "Click the Verify Address Button",
    chain: "Aurora",
    chainShortName: "AURORA",
    queryChainShortName: "AURORA",
    chainIcon: require("../assets/icon/AURORAIcon.png"),
    tokenType: "AURORA",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.3",
  },
  {
    name: "Avalanche",
    shortName: "AVAX",
    balance: "0.0",
    icon: require("../assets/icon/AVAXIcon.png"),
    cardImage: require("../assets/CardBg/Card21.png"),
    address: "Click the Verify Address Button",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    tokenType: "AVAX",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "10.0",
  },
  {
    name: "Bitcoin",
    shortName: "BTC",
    balance: "0.0",
    icon: require("../assets/icon/BTCIcon.png"),
    cardImage: require("../assets/CardBg/Card22.png"),
    address: "Click the Verify Address Button",
    chain: "Bitcoin",
    chainShortName: "BTC",
    queryChainShortName: "BTC",
    chainIcon: require("../assets/icon/BTCIcon.png"),
    tokenType: "BTC",
    fee: "0.0001",
    valueUsd: "0.0",
    priceUsd: "30000.0",
  },
  {
    name: "Bitcoin Cash",
    shortName: "BCH",
    balance: "0.0",
    icon: require("../assets/BitcoinCashIcon.png"),
    cardImage: require("../assets/CardBg/Card8.png"),
    address: "Click the Verify Address Button",
    chain: "BCH",
    chainShortName: "BCH",
    queryChainShortName: "BCH",
    chainIcon: require("../assets/icon/BCHIcon.png"),
    tokenType: "BCH",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "Binance",
    shortName: "BNB",
    balance: "0.0",
    icon: require("../assets/icon/BNBIcon.png"),
    cardImage: require("../assets/CardBg/Card41.png"),
    address: "Click the Verify Address Button",
    chain: "BNB Smart Chain",
    chainShortName: "BNB",
    queryChainShortName: "BNB",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    tokenType: "BEP20",
    fee: "0.005",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "Celo",
    shortName: "CELO",
    balance: "0.0",
    icon: require("../assets/icon/CELOIcon.png"),
    cardImage: require("../assets/CardBg/Card111.png"),
    address: "Click the Verify Address Button",
    chain: "Celo",
    chainShortName: "CELO",
    queryChainShortName: "CELO",
    chainIcon: require("../assets/icon/CELOIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Ethereum",
    shortName: "ETH",
    balance: "0.0",
    icon: require("../assets/icon/ETHIcon.png"),
    cardImage: require("../assets/CardBg/Card35.png"),
    address: "Click the Verify Address Button",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "2000.0",
  },
  {
    name: "Ethereum Classic",
    shortName: "ETC",
    balance: "0.0",
    icon: require("../assets/icon/ETCIcon.png"),
    cardImage: require("../assets/CardBg/Card62.png"),
    address: "Click the Verify Address Button",
    chain: "ETC",
    chainShortName: "ETC",
    queryChainShortName: "ETC",
    chainIcon: require("../assets/icon/ETCIcon.png"),
    tokenType: "ETC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "15.0",
  },
  {
    name: "Fantom",
    shortName: "FTM",
    balance: "0.0",
    icon: require("../assets/icon/FTMIcon.png"),
    cardImage: require("../assets/CardBg/Card45.png"),
    address: "Click the Verify Address Button",
    chain: "Fantom",
    chainShortName: "FTM",
    queryChainShortName: "FTM",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Huobi Token",
    shortName: "HTX",
    balance: "0.0",
    icon: require("../assets/icon/HTIcon.png"),
    cardImage: require("../assets/CardBg/Card56.png"),
    address: "Click the Verify Address Button",
    chain: "Huobi ECO Chain",
    chainShortName: "HTX",
    queryChainShortName: "HTX",
    chainIcon: require("../assets/icon/HTIcon.png"),
    tokenType: "ERC20",
    fee: "0.002",
    valueUsd: "0.0",
    priceUsd: "7.0",
  },
  {
    name: "IoTeX",
    shortName: "IOTX",
    balance: "0.0",
    icon: require("../assets/icon/IOTXIcon.png"),
    cardImage: require("../assets/CardBg/Card78.png"),
    address: "Click the Verify Address Button",
    chain: "IoTeX Mainnet",
    chainShortName: "IOTX",
    queryChainShortName: "IOTX",
    chainIcon: require("../assets/icon/IOTXIcon.png"),
    tokenType: "IOTX",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "Litecoin",
    shortName: "LTC",
    balance: "0.0",
    icon: require("../assets/icon/LTCIcon.png"),
    cardImage: require("../assets/CardBg/Card100.png"),
    address: "Click the Verify Address Button",
    chain: "Litecoin",
    chainShortName: "LTC",
    queryChainShortName: "LTC",
    chainIcon: require("../assets/icon/LTCIcon.png"),
    tokenType: "LTC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "150.0",
  },
  {
    name: "OKT",
    shortName: "OKT",
    balance: "0.0",
    icon: require("../assets/icon/OKBIcon.png"),
    cardImage: require("../assets/CardBg/Card106.png"),
    address: "Click the Verify Address Button",
    chain: "OKX Chain",
    chainShortName: "OKT",
    queryChainShortName: "OKT",
    chainIcon: require("../assets/icon/OKBIcon.png"),
    tokenType: "ERC20",
    fee: "0.003",
    valueUsd: "0.0",
    priceUsd: "20.0",
  },
  {
    name: "Optimism",
    shortName: "OP",
    balance: "0.0",
    icon: require("../assets/icon/OPIcon.png"),
    cardImage: require("../assets/CardBg/Card81.png"),
    address: "Click the Verify Address Button",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Polygon",
    shortName: "POL",
    balance: "0.0",
    icon: require("../assets/icon/PolygonIcon.png"),
    cardImage: require("../assets/CardBg/Card18.png"),
    address: "Click the Verify Address Button",
    chain: "Polygon",
    chainShortName: "POL",
    queryChainShortName: "POL",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.0",
  },
  {
    name: "Ripple",
    shortName: "XRP",
    balance: "0.0",
    icon: require("../assets/icon/XRPIcon.png"),
    cardImage: require("../assets/CardBg/Card84.png"),
    address: "Click the Verify Address Button",
    chain: "Ripple",
    chainShortName: "XRP",
    queryChainShortName: "XRP",
    chainIcon: require("../assets/icon/XRPIcon.png"),
    tokenType: "XRP",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Solana",
    shortName: "SOL",
    balance: "0.0",
    icon: require("../assets/icon/SOLIcon.png"),
    cardImage: require("../assets/CardBg/Card2.png"),
    address: "Click the Verify Address Button",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    tokenType: "SOL",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "25.0",
  },
  {
    name: "Tron",
    shortName: "TRX",
    balance: "0.0",
    icon: require("../assets/icon/TRXIcon.png"),
    cardImage: require("../assets/CardBg/Card97.png"),
    address: "Click the Verify Address Button",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    tokenType: "TRC20",
    fee: "0.1",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "zkSync Era",
    shortName: "ZKSYNC",
    balance: "0.0",
    icon: require("../assets/icon/ZKSIcon.png"),
    cardImage: require("../assets/CardBg/Card94.png"),
    address: "Click the Verify Address Button",
    chain: "ZKSYNC",
    chainShortName: "ZKSYNC",
    queryChainShortName: "ZKSYNC",
    chainIcon: require("../assets/icon/ZKSIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },

  // 下面是新增的
  {
    name: "Cosmos",
    shortName: "ATOM",
    balance: "0.0",
    icon: require("../assets/icon/ATOMIcon.png"),
    cardImage: require("../assets/CardBg/Card38.png"),
    address: "Click the Verify Address Button",
    chain: "Cosmos",
    chainShortName: "ATOM",
    queryChainShortName: "ATOM",
    chainIcon: require("../assets/icon/ATOMIcon.png"),
    tokenType: "ATOM",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "10.0",
  },
  {
    name: "Celestia",
    shortName: "CEL",
    balance: "0.0",
    icon: require("../assets/icon/TIAIcon.png"),
    cardImage: require("../assets/CardBg/Card51.png"),
    address: "Click the Verify Address Button",
    chain: "Celestia",
    chainShortName: "CEL",
    queryChainShortName: "CEL",
    chainIcon: require("../assets/icon/TIAIcon.png"),
    tokenType: "CEL",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "5.0",
  },
  {
    name: "Cronos",
    shortName: "CRO",
    balance: "0.0",
    icon: require("../assets/icon/CROIcon.png"),
    cardImage: require("../assets/CardBg/Card11.png"),
    address: "Click the Verify Address Button",
    chain: "Cronos",
    chainShortName: "CRO",
    queryChainShortName: "CRO",
    chainIcon: require("../assets/icon/CROIcon.png"),
    tokenType: "CRO",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.4",
  },
  {
    name: "Juno",
    shortName: "JUNO",
    balance: "0.0",
    icon: require("../assets/icon/JUNOIcon.png"),
    cardImage: require("../assets/CardBg/Card91.png"),
    address: "Click the Verify Address Button",
    chain: "Juno",
    chainShortName: "JUNO",
    queryChainShortName: "JUNO",
    chainIcon: require("../assets/icon/JUNOIcon.png"),
    tokenType: "JUNO",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "3.0",
  },
  {
    name: "Osmosis",
    shortName: "OSMO",
    balance: "0.0",
    icon: require("../assets/icon/OSMOIcon.png"),
    cardImage: require("../assets/CardBg/Card104.png"),
    address: "Click the Verify Address Button",
    chain: "Osmosis",
    chainShortName: "OSMO",
    queryChainShortName: "OSMO",
    chainIcon: require("../assets/icon/OSMOIcon.png"),
    tokenType: "OSMO",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.0",
  },
  {
    name: "Gnosis",
    shortName: "GNO",
    balance: "0.0",
    icon: require("../assets/icon/GNOIcon.png"),
    cardImage: require("../assets/CardBg/Card36.png"),
    address: "Click the Verify Address Button",
    chain: "Gnosis",
    chainShortName: "GNO",
    queryChainShortName: "GNO",
    chainIcon: require("../assets/icon/GNOIcon.png"),
    tokenType: "GNO",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "5.0",
  },
  {
    name: "Linea",
    shortName: "LINEA",
    balance: "0.0",
    icon: require("../assets/icon/LINEAIcon.png"),
    cardImage: require("../assets/CardBg/Card6.png"),
    address: "Click the Verify Address Button",
    chain: "Linea",
    chainShortName: "LINEA",
    queryChainShortName: "LINEA",
    chainIcon: require("../assets/icon/LINEAIcon.png"),
    tokenType: "LINEA",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.5",
  },
  {
    name: "Ronin",
    shortName: "RON",
    balance: "0.0",
    icon: require("../assets/icon/RONIcon.png"),
    cardImage: require("../assets/CardBg/Card83.png"),
    address: "Click the Verify Address Button",
    chain: "Ronin",
    chainShortName: "RON",
    queryChainShortName: "RON",
    chainIcon: require("../assets/icon/RONIcon.png"),
    tokenType: "RON",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.5",
  },
  {
    name: "Aptos",
    shortName: "APT",
    balance: "0.0",
    icon: require("../assets/icon/APTIcon.png"),
    cardImage: require("../assets/CardBg/Card14.png"),
    address: "Click the Verify Address Button",
    chain: "Aptos",
    chainShortName: "APT",
    queryChainShortName: "APT",
    chainIcon: require("../assets/icon/APTIcon.png"),
    tokenType: "APT",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "5.0",
  },
  {
    name: "SUI",
    shortName: "SUI",
    balance: "0.0",
    icon: require("../assets/icon/SUIIcon.png"),
    cardImage: require("../assets/CardBg/Card108.png"),
    address: "Click the Verify Address Button",
    chain: "SUI",
    chainShortName: "SUI",
    queryChainShortName: "SUI",
    chainIcon: require("../assets/icon/SUIIcon.png"),
    tokenType: "SUI",
    fee: "0.002",
    valueUsd: "0.0",
    priceUsd: "0.8",
  },
];
