// cryptosData.js
export const initialAdditionalCryptos = [
  {
    name: "Arbitrum",
    shortName: "ARB",
    balance: "0.0",
    icon: require("../assets/icon/ARBIcon.png"),
    cardImage: require("../assets/CardBg/Card13.png"),
    address: "0xxyz...",
    chain: "Arbitrum",
    chainShortName: "ARB",
    queryChainShortName: "ARB",
    chainIcon: require("../assets/icon/ARBIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.2",
  },
  {
    name: "Aurora",
    shortName: "AURORA",
    balance: "0.0",
    icon: require("../assets/icon/AURORAIcon.png"),
    cardImage: require("../assets/CardBg/Card51.png"),
    address: "aurora1xyz...",
    chain: "Aurora",
    chainShortName: "AURORA",
    queryChainShortName: "AURORA",
    chainIcon: require("../assets/icon/AURORAIcon.png"),
    tokenType: "AURORA",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.3",
  },
  {
    name: "Avalanche",
    shortName: "AVAX",
    balance: "0.0",
    icon: require("../assets/icon/AVAXIcon.png"),
    cardImage: require("../assets/CardBg/Card11.png"),
    address: "avax1xyz...",
    chain: "Avalanche",
    chainShortName: "AVAX",
    queryChainShortName: "AVAX",
    chainIcon: require("../assets/icon/AVAXIcon.png"),
    tokenType: "AVAX",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "10.0",
  },
  {
    name: "Bitcoin",
    shortName: "BTC",
    balance: "0.0",
    icon: require("../assets/icon/BTCIcon.png"),
    cardImage: require("../assets/Card3.png"),
    address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    chain: "Bitcoin",
    chainShortName: "BTC",
    queryChainShortName: "BTC",
    chainIcon: require("../assets/icon/BTCIcon.png"),
    tokenType: "BTC",
    fee: "0.0001",
    valueUsd: "0.0",
    priceUsd: "30000.0",
  },
  {
    name: "Bitcoin Cash",
    shortName: "BCH",
    balance: "0.0",
    icon: require("../assets/BitcoinCashIcon.png"),
    cardImage: require("../assets/Card2.png"),
    address: "qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a",
    chain: "Bitcoin Cash",
    chainShortName: "BCH",
    queryChainShortName: "BCH",
    chainIcon: require("../assets/icon/BCHIcon.png"),
    tokenType: "BCH",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "BNB",
    shortName: "BNB",
    balance: "0.0",
    icon: require("../assets/icon/BNBIcon.png"),
    cardImage: require("../assets/CardBg/Card32.png"),
    address: "bnb1xyz...",
    chain: "BNB Smart Chain",
    chainShortName: "BNB",
    queryChainShortName: "BNB",
    chainIcon: require("../assets/icon/BNBIcon.png"),
    tokenType: "BEP20",
    fee: "0.005",
    valueUsd: "0.0",
    priceUsd: "300.0",
  },
  {
    name: "Celo",
    shortName: "CELO",
    balance: "0.0",
    icon: require("../assets/icon/CELOIcon.png"),
    cardImage: require("../assets/CardBg/Card56.png"),
    address: "0xxyz...",
    chain: "Celo",
    chainShortName: "CELO",
    queryChainShortName: "CELO",
    chainIcon: require("../assets/icon/CELOIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Ethereum",
    shortName: "ETH",
    balance: "0.0",
    icon: require("../assets/icon/ETHIcon.png"),
    cardImage: require("../assets/Card54.png"),
    address: "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe",
    chain: "Ethereum",
    chainShortName: "ETH",
    queryChainShortName: "ETH",
    chainIcon: require("../assets/icon/ETHIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "2000.0",
  },
  {
    name: "Ethereum Classic",
    shortName: "ETC",
    balance: "0.0",
    icon: require("../assets/icon/ETCIcon.png"),
    cardImage: require("../assets/CardBg/Card21.png"),
    address: "0xxyz...",
    chain: "Ethereum Classic",
    chainShortName: "ETC",
    queryChainShortName: "ETC",
    chainIcon: require("../assets/icon/ETCIcon.png"),
    tokenType: "ETC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "15.0",
  },
  {
    name: "Fantom",
    shortName: "FTM",
    balance: "0.0",
    icon: require("../assets/icon/FTMIcon.png"),
    cardImage: require("../assets/CardBg/Card10.png"),
    address: "0xxyz...",
    chain: "Fantom",
    chainShortName: "FTM",
    queryChainShortName: "FTM",
    chainIcon: require("../assets/icon/FTMIcon.png"),
    tokenType: "ERC20",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Huobi Token",
    shortName: "HT",
    balance: "0.0",
    icon: require("../assets/icon/HTIcon.png"),
    cardImage: require("../assets/CardBg/Card14.png"),
    address: "0xxyz...",
    chain: "Huobi ECO Chain",
    chainShortName: "HT",
    queryChainShortName: "HT",
    chainIcon: require("../assets/icon/HTIcon.png"),
    tokenType: "ERC20",
    fee: "0.002",
    valueUsd: "0.0",
    priceUsd: "7.0",
  },
  {
    name: "IoTeX",
    shortName: "IOTX",
    balance: "0.0",
    icon: require("../assets/icon/IOTXIcon.png"),
    cardImage: require("../assets/CardBg/Card40.png"),
    address: "io1xyz...",
    chain: "IoTeX Network Mainnet",
    chainShortName: "IOTX",
    queryChainShortName: "IOTX",
    chainIcon: require("../assets/icon/IOTXIcon.png"),
    tokenType: "IOTX",
    fee: "0.01",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "Litecoin",
    shortName: "LTC",
    balance: "0.0",
    icon: require("../assets/icon/LTCIcon.png"),
    cardImage: require("../assets/Card1.png"),
    address: "LcHKdCbbtGxDsN7BHyebDTrVKT4w3KpU5Z",
    chain: "Litecoin",
    chainShortName: "LTC",
    queryChainShortName: "LTC",
    chainIcon: require("../assets/icon/LTCIcon.png"),
    tokenType: "LTC",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "150.0",
  },
  {
    name: "OKB",
    shortName: "OKB",
    balance: "0.0",
    icon: require("../assets/icon/OKBIcon.png"),
    cardImage: require("../assets/CardBg/Card15.png"),
    address: "0xxyz...",
    chain: "OKX Chain",
    chainShortName: "OKB",
    queryChainShortName: "OKB",
    chainIcon: require("../assets/icon/OKBIcon.png"),
    tokenType: "ERC20",
    fee: "0.003",
    valueUsd: "0.0",
    priceUsd: "20.0",
  },
  {
    name: "Optimism",
    shortName: "OP",
    balance: "0.0",
    icon: require("../assets/icon/OPIcon.png"),
    cardImage: require("../assets/CardBg/Card16.png"),
    address: "0xxyz...",
    chain: "Optimism",
    chainShortName: "OP",
    queryChainShortName: "OP",
    chainIcon: require("../assets/icon/OPIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "2.0",
  },
  {
    name: "Polygon",
    shortName: "MATIC",
    balance: "0.0",
    icon: require("../assets/icon/PolygonIcon.png"),
    cardImage: require("../assets/Card7.png"),
    address: "0xxyz...",
    chain: "Polygon",
    chainShortName: "MATIC",
    queryChainShortName: "MATIC",
    chainIcon: require("../assets/icon/PolygonIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "1.0",
  },
  {
    name: "Ripple",
    shortName: "XRP",
    balance: "0.0",
    icon: require("../assets/icon/XRPIcon.png"),
    cardImage: require("../assets/CardBg/Card24.png"),
    address: "rxyz...",
    chain: "Ripple",
    chainShortName: "XRP",
    queryChainShortName: "XRP",
    chainIcon: require("../assets/icon/XRPIcon.png"),
    tokenType: "XRP",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
  {
    name: "Solana",
    shortName: "SOL",
    balance: "0.0",
    icon: require("../assets/icon/SOLIcon.png"),
    cardImage: require("../assets/Card8.png"),
    address: "sol1xyz...",
    chain: "Solana",
    chainShortName: "SOL",
    queryChainShortName: "SOL",
    chainIcon: require("../assets/icon/SOLIcon.png"),
    tokenType: "SOL",
    fee: "0.00001",
    valueUsd: "0.0",
    priceUsd: "25.0",
  },
  {
    name: "Tron",
    shortName: "TRX",
    balance: "0.0",
    icon: require("../assets/icon/TRXIcon.png"),
    cardImage: require("../assets/CardBg/Card12.png"),
    address: "Txyz...",
    chain: "Tron",
    chainShortName: "TRX",
    queryChainShortName: "TRX",
    chainIcon: require("../assets/icon/TRXIcon.png"),
    tokenType: "TRC20",
    fee: "0.1",
    valueUsd: "0.0",
    priceUsd: "0.05",
  },
  {
    name: "zkSync Era Mainnet",
    shortName: "ZKS",
    balance: "0.0",
    icon: require("../assets/icon/ZKSIcon.png"),
    cardImage: require("../assets/CardBg/Card18.png"),
    address: "0xxyz...",
    chain: "zkSync Era Mainnet",
    chainShortName: "ZKS",
    queryChainShortName: "ZKS",
    chainIcon: require("../assets/icon/ZKSIcon.png"),
    tokenType: "ERC20",
    fee: "0.001",
    valueUsd: "0.0",
    priceUsd: "0.5",
  },
];
