// config/languages.js
export const languages = [
  { code: "en", name: "English" },
  { code: "zh", name: "简体中文" },
  { code: "zh-TW", name: "繁體中文" },
  { code: "fr", name: "Français" },
  { code: "es", name: "Español" },
  { code: "ar", name: "العربية" },
  { code: "ja", name: "日本語" },
  { code: "ru", name: "Русский" },
  { code: "ko", name: "한국어" },
  { code: "pt", name: "Português" },
  { code: "pt-BR", name: "Português (Brasil)" },
  { code: "it", name: "Italiano" },
  { code: "de", name: "Deutsch" },
  { code: "hi", name: "हिन्दी" },
  { code: "mn", name: "Монгол хэл" },
  { code: "th", name: "ไทย" },
  { code: "uk", name: "Українська" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "id", name: "Bahasa Indonesia" },
  { code: "tl", name: "Filipino" },
  { code: "bn", name: "বাংলা" },
];
