import { StyleSheet } from "react-native";
import {
  FONT_SIZE_12,
  FONT_SIZE_15,
  FONT_SIZE_16,
  FONT_SIZE_20,
  FONT_SIZE_22,
  FONT_SIZE_34,
  RADIUS_8,
  RADIUS_10,
  RADIUS_20,
  RADIUS_30,
  RADIUS_50,
} from "./constants";
const ActivityScreenStyles = (isDarkMode) => {
  const backgroundColor = isDarkMode ? "#121212" : "#f5f5f5";
  const btnBorderColor = isDarkMode ? "#CCB68C" : "#CFAB95";
  const btnColor = isDarkMode ? "#CCB68C" : "#CFAB95";
  const buttonBackgroundColor = isDarkMode ? "#CCB68C" : "#E5E1E9";
  const historyContainerBackgroundColor = isDarkMode
    ? "#22201F90"
    : "#FFFFFF80";
  const historyItemBorderColor = isDarkMode ? "#ccc" : "#999";
  const inputBackgroundColor = isDarkMode ? "#21201E" : "#e0e0e0";
  const modalBackgroundColor = isDarkMode ? "#3F3D3C" : "#fff";
  const secondBtnTextColor = isDarkMode ? "#ddd" : "#e0e0e0";
  const secondTextColor = isDarkMode ? "#ddd" : "#676776";
  const textBtnColor = isDarkMode ? "#fff" : "#fff";
  const textColor = isDarkMode ? "#fff" : "#000";
  const titleColor = isDarkMode ? "#fff" : "#000";
  const dropdownBackgroundColor = isDarkMode ? "#21201E" : "#eee";
  return StyleSheet.create({
    searchIcon: { paddingLeft: 10, color: textColor },
    searchInput: {
      flex: 1,
      padding: 10,
      borderRadius: RADIUS_10,
      color: textColor,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 10,
      width: "100%",
      backgroundColor: isDarkMode ? "#21201E" : "#E5E1E9",
      marginBottom: 20,
    },
    fromDropdown: {
      position: "absolute",
      top: 100,
      width: "100%",
      maxHeight: 300,
      backgroundColor: dropdownBackgroundColor,
      borderRadius: 10,
      padding: 10,
      zIndex: 999,
      overflow: "hidden",
    },
    toDropdown: {
      position: "absolute",
      top: 70,
      width: "100%",
      maxHeight: 300,
      backgroundColor: dropdownBackgroundColor,
      borderRadius: 10,
      padding: 10,
      zIndex: 999,
      overflow: "hidden",
    },
    chainTag: { paddingVertical: 10, paddingHorizontal: 15 },
    selectedChainTag: { backgroundColor: isDarkMode ? "#CCB68C" : "#ccc" },
    chainTagText: { color: isDarkMode ? "#fff" : "#000" },
    selectedChainTagText: { color: isDarkMode ? "#000" : "#fff" },
    container: { flex: 1, alignItems: "center" },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
    },
    swapSection: {
      width: 300,
      padding: 20,
      backgroundColor: "#1c1c1e",
      borderRadius: 10,
      marginVertical: 10,
    },
    swapInputContainer: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 2,
      borderColor: btnBorderColor,
      borderRadius: 10,
      padding: 10,
    },
    swapInput: {
      width: "100%",
      minHeight: 40,
      maxHeight: 80,
      paddingHorizontal: 10,
      color: textColor,
      textAlignVertical: "top",
    },
    tokenSelect: {
      alignSelf: "stretch",
      flexShrink: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    tokenSelectText: { color: "#fff", marginRight: 5 },
    swapButton: {
      backgroundColor: btnColor,
      padding: 6,
      borderRadius: 50,
      marginTop: -10,
      alignSelf: "flex-end",
    },
    amountInput: {
      backgroundColor: inputBackgroundColor,
      padding: 10,
      marginTop: 20,
      justifyContent: "center",
      borderRadius: 10,
      height: 60,
      alignItems: "center",
    },
    amountModalView: {
      margin: 20,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: RADIUS_20,
      padding: 30,
      alignItems: "center",
      justifyContent: "center",
      flex: 0,
    },
    amountSubtitle: {
      color: secondTextColor,
      fontSize: FONT_SIZE_15,
      marginBottom: 20,
    },
    addressText: {
      color: secondTextColor,
      flexWrap: "nowrap",
      fontSize: FONT_SIZE_15,
    },
    balanceModalSubtitle: {
      marginTop: 6,
      color: textColor,
      fontSize: FONT_SIZE_15,
      marginBottom: 16,
    },
    AssetsModalSubtitle: {
      marginTop: 6,
      color: textColor,
      fontSize: FONT_SIZE_16,
      fontSize: FONT_SIZE_16,
    },
    balanceLabel: { marginTop: 6, color: textColor, fontSize: 12 },
    AssetsValue: { color: textColor, fontSize: 12 },
    balanceSubtitle: {
      color: secondTextColor,
      fontSize: FONT_SIZE_15,
      marginBottom: 6,
    },
    bgContainer: {
      flex: 1,
      backgroundColor,
      alignItems: "center",
      padding: 20,
    },
    blurBackground: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 10,
    },
    blurView: {
      position: "absolute",
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: 10,
    },
    bluetoothImg: { width: 150, height: 150, marginBottom: 30 },
    bluetoothModalTitle: {
      color: textColor,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    bluetoothModalView: {
      margin: 20,
      height: 500,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    BluetoothBtnText: { color: "#fff", fontSize: 16 },
    buttonText: {
      color: textBtnColor,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
      marginBottom: 2,
    },
    cancelButton: {
      borderWidth: 3,
      borderColor: buttonBackgroundColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    cancelButtonLookingFor: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginTop: 20,
    },
    cancelButtonReceive: {
      borderWidth: 3,
      borderColor: buttonBackgroundColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginTop: 20,
    },
    cancelButtonText: { color: secondTextColor, fontSize: 16 },
    cancelAddressButton: {
      borderWidth: 3,
      borderColor: buttonBackgroundColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    cardContainer: {
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      width: "90%",
    },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    confirmModalView: {
      margin: 20,
      alignSelf: "center",
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    deviceItemContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    disconnectButton: {
      marginLeft: 10,
      paddingVertical: 5,
      paddingHorizontal: 10,
      backgroundColor: "#CCB68C",
      borderRadius: 5,
    },
    disconnectButtonText: { color: "#FFFFFF", fontWeight: "bold" },
    historyContainer: {
      marginTop: 15,
      padding: 10,
      paddingTop: 10,
      backgroundColor: historyContainerBackgroundColor,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 10,
      width: "96%",
      height: "76%",
    },
    historyItem: { padding: 10, marginBottom: 10 },
    historyItemText: {
      fontSize: FONT_SIZE_16,
      color: textColor,
      marginBottom: 10,
    },
    historyTitle: {
      fontSize: FONT_SIZE_16,
      color: textColor,
      fontWeight: "bold",
    },
    input: {
      backgroundColor: inputBackgroundColor,
      padding: 10,
      marginTop: 20,
      justifyContent: "center",
      borderRadius: 10,
      height: 60,
      alignItems: "center",
    },
    inputModelView: {
      margin: 20,
      height: 400,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    mainButtonText: {
      color: titleColor,
      fontSize: FONT_SIZE_15,
      fontWeight: "bold",
      marginVertical: 10,
    },
    mainSubButtonText: {
      color: historyItemBorderColor,
      fontSize: FONT_SIZE_12,
      textAlign: "center",
    },
    modalReceiveTitle: {
      color: titleColor,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
    },
    modalSubtitle: {
      color: secondTextColor,
      fontSize: FONT_SIZE_15,
      textAlign: "center",
    },
    modalText: { color: secondTextColor, textAlign: "center" },
    modalTitle: {
      color: titleColor,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
    },
    modalView: {
      margin: 20,
      height: 500,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    ConvertModalView: {
      margin: 20,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    swapModalView: {
      margin: 20,
      height: 500,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    noHistoryText: {
      fontSize: FONT_SIZE_16,
      color: secondTextColor,
      textAlign: "center",
    },
    swapConfirmButton: {
      backgroundColor: btnColor,
      padding: 10,
      width: 280,
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    optionButton: {
      backgroundColor: btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 16,
    },
    optionButtonText: { color: textBtnColor },
    passwordInput: {
      backgroundColor: inputBackgroundColor,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 10,
      height: 50,
      width: "100%",
      color: textColor,
    },
    pendingModalView: {
      margin: 20,
      width: "90%",
      height: 340,
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    SecurityCodeModalTitle: {
      color: textColor,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 15,
    },
    SecurityCodeModalView: {
      position: "absolute",
      top: 100,
      margin: 20,
      height: 400,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    receiveModalView: {
      margin: 20,
      height: 600,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    roundButton: {
      borderWidth: 2,
      borderColor: btnBorderColor,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    scanModalSubtitle: { color: secondTextColor, fontSize: FONT_SIZE_15 },
    subButtonText: { color: secondBtnTextColor, fontSize: 12 },
    submitButton: {
      backgroundColor: btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 20,
    },
    submitButtonText: { color: textBtnColor, fontSize: 16 },
    subtitleText: {
      fontSize: FONT_SIZE_15,
      color: secondTextColor,
      textAlign: "center",
      flexWrap: "wrap",
    },
    TransactionModalTitle: {
      fontSize: FONT_SIZE_16,
      color: titleColor,
      textAlign: "center",
      marginBottom: 20,
      lineHeight: 30,
    },
    transactionText: {
      color: secondTextColor,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
    },
    verifyAddressButton: {
      backgroundColor: btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 16,
    },
  });
};
export default ActivityScreenStyles;
