import { StyleSheet } from "react-native";
import {
  FONT_SIZE_12,
  FONT_SIZE_15,
  FONT_SIZE_16,
  FONT_SIZE_20,
  FONT_SIZE_22,
  FONT_SIZE_34,
  RADIUS_8,
  RADIUS_10,
  RADIUS_20,
  RADIUS_30,
} from "./constants";

import { buttonBase, modalPanelBase } from "./baseStyles";

// tokens
const makeTokens = (isDarkMode) => ({
  text: isDarkMode ? "#fff" : "#000",
  mutedText: isDarkMode ? "#ddd" : "#676776",
  bg: isDarkMode ? "#121212" : "#f5f5f5",
  btnBorder: isDarkMode ? "#CCB68C" : "#CFAB95",
  btnColor: isDarkMode ? "#CCB68C" : "#CFAB95",
  buttonBg: isDarkMode ? "#CCB68C" : "#E5E1E9",
  historyContainerBg: isDarkMode ? "#22201F90" : "#FFFFFF80",
  historyItemBorder: isDarkMode ? "#ccc" : "#999",
  inputBg: isDarkMode ? "#21201E" : "#e0e0e0",
  modalBg: isDarkMode ? "#3F3D3C" : "#fff",
  secondBtnText: isDarkMode ? "#ddd" : "#e0e0e0",
  secondText: isDarkMode ? "#ddd" : "#676776",
  textBtn: "#fff",
  title: isDarkMode ? "#fff" : "#000",
  dropdownBg: isDarkMode ? "#21201E" : "#eee",
  selectedChainTagBg: isDarkMode ? "#CCB68C" : "#ccc",
  selectedChainTagText: isDarkMode ? "#000" : "#fff",
  chainTagText: isDarkMode ? "#fff" : "#000",
});

const ActivityScreenStyles = (isDarkMode) => {
  const c = makeTokens(isDarkMode);
  return StyleSheet.create({
    searchIcon: { paddingLeft: 10, color: c.text },
    searchInput: {
      flex: 1,
      padding: 10,
      borderRadius: RADIUS_10,
      color: c.text,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 10,
      width: "100%",
      backgroundColor: c.inputBg,
      marginBottom: 20,
    },
    fromDropdown: {
      position: "absolute",
      top: 100,
      width: "100%",
      maxHeight: 300,
      backgroundColor: c.dropdownBg,
      borderRadius: 10,
      padding: 10,
      zIndex: 999,
      overflow: "hidden",
    },
    toDropdown: {
      position: "absolute",
      top: 70,
      width: "100%",
      maxHeight: 300,
      backgroundColor: c.dropdownBg,
      borderRadius: 10,
      padding: 10,
      zIndex: 999,
      overflow: "hidden",
    },
    chainTag: { paddingVertical: 10, paddingHorizontal: 15 },
    selectedChainTag: { backgroundColor: c.selectedChainTagBg },
    chainTagText: { color: c.chainTagText },
    selectedChainTagText: { color: c.selectedChainTagText },
    container: { flex: 1, alignItems: "center" },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
    },
    swapSection: {
      width: 300,
      padding: 20,
      backgroundColor: "#1c1c1e",
      borderRadius: 10,
      marginVertical: 10,
    },
    swapInputContainer: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 2,
      borderColor: c.btnBorder,
      borderRadius: 10,
      padding: 10,
    },
    swapInput: {
      width: "100%",
      minHeight: 40,
      maxHeight: 80,
      paddingHorizontal: 10,
      color: c.text,
      textAlignVertical: "top",
    },
    tokenSelect: {
      alignSelf: "stretch",
      flexShrink: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    tokenSelectText: { color: "#fff", marginRight: 5 },
    swapButton: {
      backgroundColor: c.btnColor,
      padding: 6,
      borderRadius: 50,
      marginTop: -10,
      alignSelf: "flex-end",
    },
    amountInput: {
      backgroundColor: c.inputBg,
      padding: 10,
      marginTop: 20,
      justifyContent: "center",
      borderRadius: 10,
      height: 60,
      alignItems: "center",
    },
    amountModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      justifyContent: "center",
      flex: 0,
    },
    amountSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      marginBottom: 20,
    },
    addressText: {
      color: c.secondText,
      flexWrap: "nowrap",
      fontSize: FONT_SIZE_15,
    },
    balanceModalSubtitle: {
      marginTop: 6,
      color: c.text,
      fontSize: FONT_SIZE_15,
      marginBottom: 16,
    },
    AssetsModalSubtitle: {
      marginTop: 6,
      color: c.text,
      fontSize: FONT_SIZE_16,
    },
    balanceLabel: { marginTop: 6, color: c.text, fontSize: 12 },
    AssetsValue: { color: c.text, fontSize: 12 },
    balanceSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      marginBottom: 6,
    },
    bgContainer: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: "center",
      padding: 20,
    },
    blurBackground: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 10,
    },
    blurView: {
      position: "absolute",
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: 10,
    },
    bluetoothImg: { width: 150, height: 150, marginBottom: 30 },
    bluetoothModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    bluetoothModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 500,
      justifyContent: "space-between",
    },
    BluetoothBtnText: { color: "#fff", fontSize: 16 },
    buttonText: {
      color: c.textBtn,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
      marginBottom: 2,
    },
    cancelButton: {
      ...buttonBase,
      borderWidth: 3,
      borderColor: c.buttonBg,
    },
    cancelButtonLookingFor: {
      ...buttonBase,
      borderWidth: 3,
      borderColor: c.buttonBg,
      marginTop: 20,
    },
    cancelButtonReceive: {
      ...buttonBase,
      borderWidth: 3,
      borderColor: c.buttonBg,
      marginTop: 20,
    },
    cancelButtonText: { color: c.secondText, fontSize: 16 },
    cancelAddressButton: {
      ...buttonBase,
      borderWidth: 3,
      borderColor: c.buttonBg,
    },
    cancelAddressBtn: {
      flex: 1,
      borderWidth: 3,
      borderColor: c.buttonBg,
      padding: 10,
      justifyContent: "center",
      borderRadius: 16,
      height: 60,
      alignItems: "center",
    },
    cardContainer: {
      backgroundColor: c.modalBg,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      width: "90%",
    },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    confirmModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    deviceItemContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    disconnectButton: {
      marginLeft: 10,
      paddingVertical: 5,
      paddingHorizontal: 10,
      backgroundColor: "#CCB68C",
      borderRadius: 5,
    },
    disconnectButtonText: { color: "#FFFFFF", fontWeight: "bold" },
    historyContainer: {
      marginTop: 15,
      padding: 10,
      paddingTop: 10,
      backgroundColor: c.historyContainerBg,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 10,
      width: "96%",
      height: "76%",
    },
    historyItem: { padding: 10, marginBottom: 10 },
    historyItemText: {
      fontSize: FONT_SIZE_16,
      color: c.text,
      marginBottom: 10,
    },
    historyTitle: {
      fontSize: FONT_SIZE_16,
      color: c.title,
      fontWeight: "bold",
    },
    input: {
      backgroundColor: c.inputBg,
      padding: 10,
      marginTop: 20,
      justifyContent: "center",
      borderRadius: 10,
      height: 60,
      alignItems: "center",
    },
    inputModelView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 400,
    },
    mainButtonText: {
      color: c.title,
      fontSize: FONT_SIZE_15,
      fontWeight: "bold",
      marginVertical: 10,
    },
    mainSubButtonText: {
      color: c.historyItemBorder,
      fontSize: FONT_SIZE_12,
      textAlign: "center",
    },
    modalReceiveTitle: {
      color: c.title,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
    },
    modalSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      textAlign: "center",
    },
    modalText: { color: c.secondText, textAlign: "center" },
    modalTitle: {
      color: c.title,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
    },
    modalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 500,
      justifyContent: "space-between",
    },
    ConvertModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    swapModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 500,
      justifyContent: "space-between",
    },
    noHistoryText: {
      fontSize: FONT_SIZE_16,
      color: c.secondText,
      textAlign: "center",
    },
    swapConfirmButton: {
      backgroundColor: c.btnColor,
      padding: 10,
      width: 280,
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    optionButton: {
      backgroundColor: c.btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 16,
    },
    optionButtonText: { color: c.textBtn },
    passwordInput: {
      backgroundColor: c.inputBg,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 10,
      height: 50,
      width: "100%",
      color: c.text,
    },
    pendingModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 340,
      justifyContent: "space-between",
    },
    SecurityCodeModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 15,
    },
    SecurityCodeModalView: {
      position: "absolute",
      top: 100,
      margin: 20,
      height: 400,
      width: "90%",
      backgroundColor: c.modalBg,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    receiveModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 600,
      justifyContent: "space-between",
    },
    roundButton: {
      borderWidth: 2,
      borderColor: c.btnBorder,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    scanModalSubtitle: { color: c.secondText, fontSize: FONT_SIZE_15 },
    subButtonText: { color: c.secondBtnText, fontSize: 12 },
    submitButton: {
      backgroundColor: c.btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 20,
    },
    submitButtonText: { color: c.textBtn, fontSize: 16 },
    subtitleText: {
      fontSize: FONT_SIZE_15,
      color: c.secondText,
      textAlign: "center",
      flexWrap: "wrap",
    },
    TransactionModalTitle: {
      fontSize: FONT_SIZE_16,
      color: c.title,
      textAlign: "center",
      marginBottom: 20,
      lineHeight: 30,
    },
    transactionText: {
      color: c.secondText,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
    },
    verifyAddressButton: {
      backgroundColor: c.btnColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 16,
    },
    verifyAddressBtn: {
      flex: 1,
      backgroundColor: c.btnColor,
      padding: 10,
      justifyContent: "center",
      borderRadius: 16,
      height: 60,
      alignItems: "center",
      marginBottom: 16,
    },
  });
};

export default ActivityScreenStyles;
