import { StyleSheet } from "react-native";
import {
  FONT_SIZE_12,
  FONT_SIZE_15,
  FONT_SIZE_16,
  FONT_SIZE_20,
  FONT_SIZE_22,
  FONT_SIZE_34,
  RADIUS_8,
  RADIUS_10,
  RADIUS_20,
  RADIUS_30,
} from "./constants";

import { buttonBase, modalPanelBase } from "./baseStyles";

// tokens
const makeTokens = (isDarkMode) => ({
  text: isDarkMode ? "#fff" : "#000",
  bg: isDarkMode ? "#121212" : "#f5f5f5",
  modalBg: isDarkMode ? "#3F3D3C" : "#fff",
  currencyModalBg: isDarkMode ? "#3F3D3C" : "#f7f7f7",
  buttonBg: isDarkMode ? "#CCB68C" : "#E5E1E9",
  border: isDarkMode ? "#404040" : "#ccc",
  bluetoothBtn: isDarkMode ? "#CCB68C" : "#CFAB95",
  mutedText: isDarkMode ? "#ddd" : "#676776",
  inputBg: isDarkMode ? "#21201E" : "#e0e0e0",
  focusedBorder: isDarkMode ? "#CCB68C" : "#CFAB95",
  secondText: isDarkMode ? "#ddd" : "#676776",
  cancelBtnText: isDarkMode ? "#ddd" : "#676776",
  dropdownBg: isDarkMode ? "#3F3D3C" : "#fff",
  dropdownText: isDarkMode ? "#fff" : "#000",
});

const SecureDeviceScreenStyles = (isDarkMode) => {
  const c = makeTokens(isDarkMode);
  return StyleSheet.create({
    addressInput: {
      backgroundColor: c.inputBg,
      padding: 15,
      paddingTop: 15,
      borderRadius: RADIUS_10,
      height: 120,
      width: "100%",
      color: c.text,
    },
    addressModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    bluetoothImg: { width: 150, height: 150, marginBottom: 30 },
    bluetoothModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    bluetoothModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 500,
      justifyContent: "space-between",
    },
    BluetoothBtnText: { color: "#fff", fontSize: FONT_SIZE_16 },
    buttonContainer: {
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
    },
    AddressBookContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      gap: 10,
    },
    buttonText: { color: c.text, fontSize: FONT_SIZE_16 },
    cancelButton: {
      ...buttonBase,
      borderColor: c.buttonBg,
      borderWidth: 3,
    },
    cancelButtonLookingFor: {
      ...buttonBase,
      borderColor: c.buttonBg,
      borderWidth: 3,
      marginTop: 20,
    },
    cancelButtonText: { color: c.cancelBtnText, fontSize: FONT_SIZE_16 },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    changeLockCodeModalView: {
      position: "absolute",
      top: 60,
      ...modalPanelBase,
      height: 330,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    closeButton: {
      ...buttonBase,
      borderColor: c.buttonBg,
      borderWidth: 3,
    },
    backButton: {
      flex: 1,
      borderColor: c.buttonBg,
      borderWidth: 3,
      padding: 10,
      justifyContent: "center",
      borderRadius: 15,
      height: 60,
      alignItems: "center",
    },
    container: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 10,
      paddingLeft: 20,
      paddingRight: 20,
    },
    contentContainer: { flexGrow: 1 },
    currencyModalView: {
      ...modalPanelBase,
      backgroundColor: c.currencyModalBg,
      height: 420,
    },
    deviceIcon: { paddingRight: 4 },
    deviceItemContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    disableLockModalView: {
      position: "absolute",
      top: 60,
      ...modalPanelBase,
      height: 320,
      backgroundColor: c.modalBg,
    },
    disconnectButton: {
      marginLeft: 10,
      paddingVertical: 5,
      paddingHorizontal: 10,
      backgroundColor: "#CCB68C",
      borderRadius: 5,
    },
    disconnectButtonText: { color: "#FFFFFF", fontWeight: "bold" },
    disconnectModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 340,
      justifyContent: "space-between",
    },
    disconnectSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      textAlign: "center",
      marginTop: 20,
    },
    dropdown: {
      position: "absolute",
      right: 20,
      top: 2,
      backgroundColor: c.dropdownBg,
      borderRadius: 5,
      paddingVertical: 8,
      paddingHorizontal: 16,
      zIndex: 101,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    dropdownButtonText: {
      color: c.dropdownText,
      fontSize: FONT_SIZE_15,
      paddingVertical: 5,
    },
    enableLockModalView: {
      position: "absolute",
      top: 60,
      ...modalPanelBase,
      height: 400,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    EnterLockCodeModalView: {
      position: "absolute",
      top: 100,
      justifyContent: "space-between",
      ...modalPanelBase,
      height: 360,
      backgroundColor: c.modalBg,
    },
    errorText: {
      color: "#FF5252",
      fontSize: FONT_SIZE_15,
      marginBottom: 10,
      width: 280,
    },
    eyeIcon: {
      position: "absolute",
      right: 15,
      top: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    Icon: { marginRight: 6 },
    focusedInput: { borderColor: c.focusedBorder, borderWidth: 2 },
    focusedSearchContainer: { borderColor: c.focusedBorder, borderWidth: 2 },
    languageCancelButton: {
      ...buttonBase,
      borderColor: c.buttonBg,
      borderWidth: 3,
      width: "90%",
      position: "absolute",
      bottom: 30,
      marginTop: 20,
    },
    languageList: { maxHeight: 290, width: 280 },
    languageModalText: {
      color: c.text,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
      textAlign: "center",
    },
    currencyModalText: { color: c.text, fontSize: 16, textAlign: "center" },
    languageModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 30,
    },
    languageModalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
      height: 420,
    },
    listContainer: { flexDirection: "row", alignItems: "center", flex: 1 },
    modalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
      marginBottom: 15,
    },
    modalSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      textAlign: "center",
    },
    modalView: {
      ...modalPanelBase,
      backgroundColor: c.modalBg,
    },
    passwordInput: {
      backgroundColor: c.inputBg,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 10,
      height: 50,
      width: "100%",
      color: c.text,
      marginBottom: 10,
    },
    passwordInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      position: "relative",
    },
    LockCodeModalText: {
      color: c.text,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
      textAlign: "left",
    },
    LockCodeModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    SecurityCodeModalTitle: {
      color: c.text,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 15,
    },
    SecurityCodeModalView: {
      position: "absolute",
      top: 100,
      ...modalPanelBase,
      height: 400,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    roundButton: {
      backgroundColor: c.bluetoothBtn,
      borderRadius: 30,
      paddingVertical: 10,
      paddingHorizontal: 20,
      width: "100%",
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    scanModalSubtitle: {
      color: c.secondText,
      fontSize: FONT_SIZE_15,
      textAlign: "center",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 10,
      width: "100%",
      backgroundColor: c.inputBg,
      marginBottom: 20,
    },
    searchIcon: { paddingLeft: 10, color: c.text },
    searchInput: { flex: 1, padding: 10, borderRadius: 10, color: c.text },
    setLockCodeModalView: {
      position: "absolute",
      top: 60,
      ...modalPanelBase,
      height: 420,
      backgroundColor: c.modalBg,
      justifyContent: "space-between",
    },
    settingsItem: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    scrollView: { width: "100%" },
    submitButton: {
      ...buttonBase,
      backgroundColor: c.buttonBg,
      marginBottom: 15,
    },
    confirmButton: {
      ...buttonBase,
      backgroundColor: c.buttonBg,
    },
    saveButton: {
      flex: 1,
      backgroundColor: c.buttonBg,
      padding: 10,
      justifyContent: "center",
      borderRadius: 15,
      height: 60,
      alignItems: "center",
    },
    submitButtonText: { color: c.text, fontSize: FONT_SIZE_16 },
    Text: { color: c.text, fontSize: FONT_SIZE_16 },
  });
};

export default SecureDeviceScreenStyles;
