// styles/SecureDeviceScreenStyle.js
import { StyleSheet } from "react-native";
import {
  FONT_SIZE_12,
  FONT_SIZE_15,
  FONT_SIZE_16,
  FONT_SIZE_20,
  FONT_SIZE_22,
  FONT_SIZE_34,
  RADIUS_5,
  RADIUS_10,
  RADIUS_20,
  RADIUS_30,
  RADIUS_50,
  FOCUSED_BORDER_COLOR_DARK,
  FOCUSED_BORDER_COLOR_LIGHT,
  PURE_WHITE,
  ERROR_COLOR,
  BLACK,
  TRANSPARENT_BLACK_20,
  lightColors,
  darkColors,
} from "./constants";

const SecureDeviceScreenStyles = (isDarkMode) => {
  const colors = isDarkMode ? darkColors : lightColors;
  const focusedBorderColor = isDarkMode
    ? FOCUSED_BORDER_COLOR_DARK
    : FOCUSED_BORDER_COLOR_LIGHT;

  return StyleSheet.create({
    addressInput: {
      backgroundColor: colors.inputBackgroundColor,
      padding: 15,
      paddingTop: 15,
      borderRadius: RADIUS_10,
      height: 120,
      width: "100%",
      color: colors.textColor,
    },
    addressModalView: {
      margin: 20,
      width: "90%",
      backgroundColor: colors.modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    bluetoothImg: {
      width: 150,
      height: 150,
      marginBottom: 30,
    },
    bluetoothModalTitle: {
      color: colors.textColor,
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    bluetoothModalView: {
      margin: 20,
      height: 500,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    BluetoothBtnText: {
      color: "#fff",
      fontSize: FONT_SIZE_16,
    },
    buttonContainer: {
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
    },
    AddressBookContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",

      gap: 10,
    },
    buttonText: {
      color: textColor,
      fontSize: 16,
    },
    cancelButton: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    cancelButtonLookingFor: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginTop: 20,
    },
    cancelButtonText: {
      color: colors.secondTextColor,
      fontSize: 16,
    },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: TRANSPARENT_BLACK_20,
    },
    changeLockCodeModalView: {
      position: "absolute",
      top: 60,
      margin: 20,
      height: 330,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    closeButton: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    backButton: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      flex: 1,
      justifyContent: "center",
      borderRadius: 15,
      height: 60,
      alignItems: "center",
    },
    container: {
      flex: 1,
      backgroundColor,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 10,
      paddingLeft: 20,
      paddingRight: 20,
    },
    contentContainer: {
      flexGrow: 1,
    },
    currencyModalView: {
      margin: 20,
      height: 420,
      width: "90%",
      backgroundColor: colors.modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    deviceIcon: {
      paddingRight: 4,
    },
    deviceItemContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    disableLockModalView: {
      position: "absolute",
      top: 60,
      margin: 20,
      height: 320,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    disconnectButton: {
      marginLeft: 10,
      paddingVertical: 5,
      paddingHorizontal: 10,
      backgroundColor: darkColors.buttonBackgroundColor,
      borderRadius: 5,
    },
    disconnectButtonText: {
      color: PURE_WHITE,
      fontWeight: "bold",
    },
    disconnectModalView: {
      margin: 20,
      height: 340,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    disconnectSubtitle: {
      color: colors.secondTextColor,
      fontSize: 14,
      textAlign: "center",
      marginTop: 20,
    },
    dropdown: {
      position: "absolute",
      right: 20,
      top: 2,
      backgroundColor: modalBackgroundColor,
      borderRadius: 5,
      paddingVertical: 8,
      paddingHorizontal: 16,
      zIndex: 101,
      shadowColor: BLACK,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    dropdownButtonText: {
      color: textColor,
      fontSize: 14,
      paddingVertical: 5,
    },
    enableLockModalView: {
      position: "absolute",
      top: 60,
      margin: 20,
      height: 400,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    EnterLockCodeModalView: {
      position: "absolute",
      top: 100,
      justifyContent: "space-between",
      margin: 20,
      height: 360,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    errorText: {
      color: ERROR_COLOR,
      fontSize: 14,
      marginBottom: 10,
      width: 280,
    },
    eyeIcon: {
      position: "absolute",
      right: 15,
      top: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    Icon: {
      marginRight: 6,
    },
    focusedInput: {
      borderColor: focusedBorderColor,
      borderWidth: 2,
    },
    focusedSearchContainer: {
      borderColor: focusedBorderColor,
      borderWidth: 2,
    },
    languageCancelButton: {
      borderColor: buttonBackgroundColor,
      borderWidth: 3,
      padding: 10,
      width: "90%",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      position: "absolute",
      bottom: 30,
      marginTop: 20,
    },
    languageList: {
      maxHeight: 290,
      width: 280,
    },
    languageModalText: {
      color: textColor,
      fontSize: 16,
      marginBottom: 10,
      textAlign: "center",
    },
    currencyModalText: {
      color: textColor,
      fontSize: 16,
      textAlign: "center",
    },
    languageModalTitle: {
      color: textColor,
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 30,
    },
    languageModalView: {
      margin: 20,
      height: 420,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    listContainer: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    modalSubtitle: {
      color: secondTextColor,
      fontSize: 14,
      textAlign: "center",
    },
    modalTitle: {
      color: textColor,
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 15,
    },
    modalView: {
      margin: 20,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
    },
    passwordInput: {
      backgroundColor: inputBackgroundColor,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 10,
      height: 50,
      width: "100%",
      color: textColor,
      marginBottom: 10,
    },
    passwordInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      position: "relative",
    },
    LockCodeModalText: {
      color: textColor,
      fontSize: 16,
      marginBottom: 10,
      textAlign: "left",
    },
    LockCodeModalTitle: {
      color: textColor,
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    SecurityCodeModalTitle: {
      color: textColor,
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 15,
    },
    SecurityCodeModalView: {
      position: "absolute",
      top: 100,
      margin: 20,
      height: 400,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      justifyContent: "space-between",
      alignItems: "center",
    },
    roundButton: {
      backgroundColor: colors.BluetoothBtnColor,
      borderRadius: 30,
      paddingVertical: 10,
      paddingHorizontal: 20,
      width: "100%",
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    scanModalSubtitle: {
      color: secondTextColor,
      fontSize: 14,
      textAlign: "center",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 10,
      width: "100%",
      backgroundColor: isDarkMode
        ? darkColors.dropdownBackgroundColor
        : lightColors.buttonBackgroundColor,
      marginBottom: 20,
    },
    searchIcon: {
      paddingLeft: 10,
      color: textColor,
    },
    searchInput: {
      flex: 1,
      padding: 10,
      borderRadius: 10,
      color: textColor,
    },
    setLockCodeModalView: {
      position: "absolute",
      top: 60,
      margin: 20,
      height: 420,
      width: "90%",
      backgroundColor: modalBackgroundColor,
      borderRadius: 20,
      padding: 30,
      alignItems: "center",
      justifyContent: "space-between",
    },
    settingsItem: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderColor,
    },
    scrollView: {
      width: "100%",
    },
    submitButton: {
      backgroundColor: colors.buttonBackgroundColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
      marginBottom: 15,
    },
    confirmButton: {
      backgroundColor: buttonBackgroundColor,
      padding: 10,
      width: "100%",
      justifyContent: "center",
      borderRadius: 30,
      height: 60,
      alignItems: "center",
    },
    saveButton: {
      backgroundColor: buttonBackgroundColor,
      padding: 10,
      flex: 1,
      justifyContent: "center",
      borderRadius: 15,
      height: 60,
      alignItems: "center",
    },

    submitButtonText: {
      color: textColor,
      fontSize: 16,
    },
    Text: {
      color: textColor,
      fontSize: 16,
    },
  });
};

export default SecureDeviceScreenStyles;
