import { StyleSheet } from "react-native";
import {
  FONT_SIZE_12,
  FONT_SIZE_15,
  FONT_SIZE_16,
  FONT_SIZE_20,
  FONT_SIZE_22,
  FONT_SIZE_28,
  FONT_SIZE_34,
  RADIUS_8,
  RADIUS_10,
  RADIUS_12,
  RADIUS_16,
  RADIUS_20,
  RADIUS_30,
} from "./constants";

import { buttonBase, modalPanelBase } from "./baseStyles";

// tokens
const makeTokens = (isDarkMode) => ({
  text: isDarkMode ? "#fff" : "#21201E",
  mutedText: isDarkMode ? "#ddd" : "#676776",
  bg: isDarkMode ? "#121212" : "#ddd",
  headerBg: isDarkMode ? "#21201E" : "#fff",
  headerRightBg: isDarkMode ? "#21201E" : "#ddd",
  addIconBtnBg: isDarkMode ? "#21201E" : "#fff",
  dropdownBg: isDarkMode ? "#3F3D3C" : "#E5E1E9",
  dropdownText: isDarkMode ? "#fff" : "#000",
  cardBg: isDarkMode ? "#3F3D3C" : "#fff",
  cardText: isDarkMode ? "#fff" : "#000",
  overlay: "rgba(108, 108, 244, 0.1)",
  roundBtnBg: isDarkMode ? "#3F3D3C" : "#3F3D3C",
  buttonText: isDarkMode ? "#e0e0e0" : "#e0e0e0",
  modalBg: isDarkMode ? "#3F3D3C" : "#fff",
  modalTitle: "#ffffff",
  modalSubtitle: "#e0e0e0",
  languageModalBg: isDarkMode ? "#3F3D3C" : "#fff",
  languageModalText: "#ffffff",
  languageCancelBtnBg: "#CCB68C",
  historyBg: isDarkMode ? "#21201E" : "#E5E1E9",
  historyTitle: "#ffffff",
  noHistoryText: "#ffffff",
  historyItemBorder: "#ccc",
  historyItemText: "#000",
  optionBtnBg: "#CCB68C",
  inputBg: isDarkMode ? "#21201E" : "#E5E1E9",
  submitBtnBg: "#CCB68C",
  cancelBtnBg: "#CCB68C",
  submitBtnText: "#ffffff",
  cancelBtnText: "#ffffff",
});

const stylesFactory = (isDarkMode) => {
  const c = makeTokens(isDarkMode);
  return StyleSheet.create({
    settingsText: { marginLeft: 10, fontSize: FONT_SIZE_16, color: c.text },
    titleText: {
      color: c.text,
      fontSize: FONT_SIZE_28,
      fontWeight: "bold",
      marginBottom: 20,
    },
    container: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
    },
    headerStyle: { backgroundColor: c.headerBg },
    headerRight: { backgroundColor: c.headerRightBg },
    addIconButton: { backgroundColor: c.addIconBtnBg },
    addIconButtonCommon: {
      marginRight: 16,
      borderRadius: RADIUS_16,
      width: 28,
      height: 28,
      justifyContent: "center",
      alignItems: "center",
    },
    dropdown: {
      position: "absolute",
      right: 20,
      top: 60,
      backgroundColor: c.dropdownBg,
      borderRadius: RADIUS_8,
      padding: 10,
      zIndex: 1,
    },
    dropdownButton: { padding: 10 },
    dropdownButtonText: { color: c.dropdownText, fontSize: FONT_SIZE_16 },
    scrollView: { width: "100%" },
    contentContainer: { flexGrow: 1 },
    settingsItem: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#404040",
    },
    safeArea: { flex: 1, backgroundColor: c.bg },
    card: {
      width: 300,
      height: 170,
      borderRadius: RADIUS_20,
      overflow: "hidden",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: c.cardBg,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    cardText: { color: c.cardText, fontSize: FONT_SIZE_16, fontWeight: "bold" },
    roundButton: {
      backgroundColor: c.roundBtnBg,
      borderRadius: RADIUS_30,
      paddingVertical: 10,
      paddingHorizontal: 20,
      width: "100%",
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    buttonText: {
      color: c.buttonText,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
    },
    subButtonText: { color: c.buttonText, fontSize: 12 },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    modalView: { ...modalPanelBase, backgroundColor: c.modalBg, height: 500 },
    modalTitle: {
      color: c.modalTitle,
      fontSize: FONT_SIZE_16,
      fontWeight: "bold",
      marginBottom: 15,
    },
    modalSubtitle: {
      color: c.modalSubtitle,
      fontSize: FONT_SIZE_16,
      marginBottom: 320,
      textAlign: "center",
    },
    languageModalTitle: {
      color: c.languageModalText,
      fontSize: FONT_SIZE_20,
      fontWeight: "bold",
      marginBottom: 30,
    },
    languageModalText: {
      color: c.languageModalText,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
      textAlign: "center",
    },
    LockCodeModalText: {
      color: c.languageModalText,
      fontSize: FONT_SIZE_16,
      marginBottom: 10,
      textAlign: "left",
    },
    languageList: { maxHeight: 320, width: 280 },
    languageCancelButton: {
      backgroundColor: c.languageCancelBtnBg,
      padding: 10,
      width: "90%",
      borderRadius: RADIUS_30,
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      position: "absolute",
      bottom: 30,
    },
    historyContainer: {
      marginTop: 20,
      padding: 20,
      backgroundColor: c.historyBg,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: RADIUS_10,
      height: 360,
    },
    historyTitle: {
      position: "absolute",
      left: 20,
      top: 20,
      fontSize: FONT_SIZE_16,
      color: c.historyTitle,
    },
    noHistoryText: {
      fontSize: FONT_SIZE_16,
      color: c.noHistoryText,
      textAlign: "center",
    },
    historyItem: {
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.historyItemBorder,
    },
    historyItemText: { fontSize: FONT_SIZE_16, color: c.historyItemText },
    modalText: { color: c.modalTitle, textAlign: "center", marginBottom: 120 },
    optionButton: {
      ...buttonBase,
      backgroundColor: c.optionBtnBg,
      marginBottom: 10,
    },
    optionButtonText: { color: c.modalTitle },
    input: {
      backgroundColor: c.inputBg,
      padding: 10,
      marginTop: 30,
      marginBottom: 60,
      justifyContent: "center",
      borderRadius: RADIUS_10,
      height: 60,
      alignItems: "center",
    },
    submitButton: {
      ...buttonBase,
      backgroundColor: c.submitBtnBg,
      marginBottom: 0,
    },
    cancelButton: {
      ...buttonBase,
      backgroundColor: c.cancelBtnBg,
      position: "absolute",
      bottom: 60,
    },
    submitButtonText: { color: c.submitBtnText },
    cancelButtonText: { color: c.cancelBtnText },
  });
};

export const lightTheme = stylesFactory(false);
export const darkTheme = stylesFactory(true);
export default stylesFactory;
